### ISSUE TITLE
Error: ConnectFailure (Connection refused)

### ISSUE THREAD

**Issue by health365** [schneidsDotNet/Xamarin-Forms-and-SignalR-Example#1]
Hi, 
     When I used your example, I got a connection error. My dev environment is: VS2015 with Parallels desktop.
I'm a freshman for Xamrin & SignalR, could you please give me some hint to solve this issue?
Thanks a lot.

System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect...

**Comment by schneidenbach** [comment]
Unfortunately, I haven't used Xamarin in over a year, so I won't be of much help.  You should make sure that you're running both the client and server solution.  Also, I've had comments that the Android version has trouble connecting to the server when running in the simulator.

Good luck!
